[tasks.csv]
script = '''
cargo run -- --input ./example/test.md --output test.csv --format CSV -p
'''

[tasks.ast]
script = '''
cargo run -- --input ./example/test.md --output test.json --format AST -p
'''

[tasks.wasm_build]
script = '''
wasm-pack build --target web
'''

[tasks.wasm_deploy]
script = '''
wasm-pack build --target web

cd pkg

rm .gitignore

git init
git add -A
git commit
git push git@github.com:chmlee/ream-wasm.git master

cd -
'''

[tasks.wasm_serve]
script = '''
python -m http.server -d ./pkg
'''
